//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWCF.Webservice_IDLT {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DLT", Namespace="http://119.46.91.238/")]
    [System.SerializableAttribute()]
    public partial class DLT : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Result01Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Result02Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Result03Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Result04Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Result05Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Result06Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Result07Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Result08Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Result01 {
            get {
                return this.Result01Field;
            }
            set {
                if ((object.ReferenceEquals(this.Result01Field, value) != true)) {
                    this.Result01Field = value;
                    this.RaisePropertyChanged("Result01");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Result02 {
            get {
                return this.Result02Field;
            }
            set {
                if ((object.ReferenceEquals(this.Result02Field, value) != true)) {
                    this.Result02Field = value;
                    this.RaisePropertyChanged("Result02");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Result03 {
            get {
                return this.Result03Field;
            }
            set {
                if ((object.ReferenceEquals(this.Result03Field, value) != true)) {
                    this.Result03Field = value;
                    this.RaisePropertyChanged("Result03");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Result04 {
            get {
                return this.Result04Field;
            }
            set {
                if ((object.ReferenceEquals(this.Result04Field, value) != true)) {
                    this.Result04Field = value;
                    this.RaisePropertyChanged("Result04");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Result05 {
            get {
                return this.Result05Field;
            }
            set {
                if ((object.ReferenceEquals(this.Result05Field, value) != true)) {
                    this.Result05Field = value;
                    this.RaisePropertyChanged("Result05");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Result06 {
            get {
                return this.Result06Field;
            }
            set {
                if ((object.ReferenceEquals(this.Result06Field, value) != true)) {
                    this.Result06Field = value;
                    this.RaisePropertyChanged("Result06");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Result07 {
            get {
                return this.Result07Field;
            }
            set {
                if ((object.ReferenceEquals(this.Result07Field, value) != true)) {
                    this.Result07Field = value;
                    this.RaisePropertyChanged("Result07");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Result08 {
            get {
                return this.Result08Field;
            }
            set {
                if ((object.ReferenceEquals(this.Result08Field, value) != true)) {
                    this.Result08Field = value;
                    this.RaisePropertyChanged("Result08");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://119.46.91.238/", ConfigurationName="Webservice_IDLT.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name Username from namespace http://119.46.91.238/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://119.46.91.238/Login", ReplyAction="*")]
        PWCF.Webservice_IDLT.LoginResponse Login(PWCF.Webservice_IDLT.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name TOKEN_ID from namespace http://119.46.91.238/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://119.46.91.238/P_CAL_TAX_MBL", ReplyAction="*")]
        PWCF.Webservice_IDLT.P_CAL_TAX_MBLResponse P_CAL_TAX_MBL(PWCF.Webservice_IDLT.P_CAL_TAX_MBLRequest request);
        
        // CODEGEN: Generating message contract since element name TOKEN_ID from namespace http://119.46.91.238/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://119.46.91.238/P_RECV_TAX_MBL", ReplyAction="*")]
        PWCF.Webservice_IDLT.P_RECV_TAX_MBLResponse P_RECV_TAX_MBL(PWCF.Webservice_IDLT.P_RECV_TAX_MBLRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://119.46.91.238/", Order=0)]
        public PWCF.Webservice_IDLT.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(PWCF.Webservice_IDLT.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://119.46.91.238/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string Username, string Password) {
            this.Username = Username;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://119.46.91.238/", Order=0)]
        public PWCF.Webservice_IDLT.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(PWCF.Webservice_IDLT.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://119.46.91.238/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class P_CAL_TAX_MBLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="P_CAL_TAX_MBL", Namespace="http://119.46.91.238/", Order=0)]
        public PWCF.Webservice_IDLT.P_CAL_TAX_MBLRequestBody Body;
        
        public P_CAL_TAX_MBLRequest() {
        }
        
        public P_CAL_TAX_MBLRequest(PWCF.Webservice_IDLT.P_CAL_TAX_MBLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://119.46.91.238/")]
    public partial class P_CAL_TAX_MBLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TOKEN_ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SOFF_NAME;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SBR_NAME;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string STYPE_NAME;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SPLATE1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SPLATE2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string SID_NO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string SNAME;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string STEL_NO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string SPOLICY_FLAG;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string SPOLICY_NO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string SPOLICY_END;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string SADV_FLAG;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string SPHONE_NETW;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string SIDTAX_NETW;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string SOPR_PAY;
        
        public P_CAL_TAX_MBLRequestBody() {
        }
        
        public P_CAL_TAX_MBLRequestBody(
                    string TOKEN_ID, 
                    string SOFF_NAME, 
                    string SBR_NAME, 
                    string STYPE_NAME, 
                    string SPLATE1, 
                    string SPLATE2, 
                    string SID_NO, 
                    string SNAME, 
                    string STEL_NO, 
                    string SPOLICY_FLAG, 
                    string SPOLICY_NO, 
                    string SPOLICY_END, 
                    string SADV_FLAG, 
                    string SPHONE_NETW, 
                    string SIDTAX_NETW, 
                    string SOPR_PAY) {
            this.TOKEN_ID = TOKEN_ID;
            this.SOFF_NAME = SOFF_NAME;
            this.SBR_NAME = SBR_NAME;
            this.STYPE_NAME = STYPE_NAME;
            this.SPLATE1 = SPLATE1;
            this.SPLATE2 = SPLATE2;
            this.SID_NO = SID_NO;
            this.SNAME = SNAME;
            this.STEL_NO = STEL_NO;
            this.SPOLICY_FLAG = SPOLICY_FLAG;
            this.SPOLICY_NO = SPOLICY_NO;
            this.SPOLICY_END = SPOLICY_END;
            this.SADV_FLAG = SADV_FLAG;
            this.SPHONE_NETW = SPHONE_NETW;
            this.SIDTAX_NETW = SIDTAX_NETW;
            this.SOPR_PAY = SOPR_PAY;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class P_CAL_TAX_MBLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="P_CAL_TAX_MBLResponse", Namespace="http://119.46.91.238/", Order=0)]
        public PWCF.Webservice_IDLT.P_CAL_TAX_MBLResponseBody Body;
        
        public P_CAL_TAX_MBLResponse() {
        }
        
        public P_CAL_TAX_MBLResponse(PWCF.Webservice_IDLT.P_CAL_TAX_MBLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://119.46.91.238/")]
    public partial class P_CAL_TAX_MBLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PWCF.Webservice_IDLT.DLT P_CAL_TAX_MBLResult;
        
        public P_CAL_TAX_MBLResponseBody() {
        }
        
        public P_CAL_TAX_MBLResponseBody(PWCF.Webservice_IDLT.DLT P_CAL_TAX_MBLResult) {
            this.P_CAL_TAX_MBLResult = P_CAL_TAX_MBLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class P_RECV_TAX_MBLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="P_RECV_TAX_MBL", Namespace="http://119.46.91.238/", Order=0)]
        public PWCF.Webservice_IDLT.P_RECV_TAX_MBLRequestBody Body;
        
        public P_RECV_TAX_MBLRequest() {
        }
        
        public P_RECV_TAX_MBLRequest(PWCF.Webservice_IDLT.P_RECV_TAX_MBLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://119.46.91.238/")]
    public partial class P_RECV_TAX_MBLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TOKEN_ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SPHONE_NETW;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SREF_NO1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SRECV_DATE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SRECV_AMT;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SSEND_NAME;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string SSEND_ADDR;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string SSEND_DIST;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string SSEND_AMP;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string SSEND_PRV;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string SSEND_ZIP;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string SINS_NAME;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string SINS_BUILD;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string SINS_ADDR;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string SINS_MOO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string SINS_SOI;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string SINS_ROAD;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string SINS_DIST;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string SINS_AMP;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string SINS_PRV;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string SINS_ZIP;
        
        public P_RECV_TAX_MBLRequestBody() {
        }
        
        public P_RECV_TAX_MBLRequestBody(
                    string TOKEN_ID, 
                    string SPHONE_NETW, 
                    string SREF_NO1, 
                    string SRECV_DATE, 
                    string SRECV_AMT, 
                    string SSEND_NAME, 
                    string SSEND_ADDR, 
                    string SSEND_DIST, 
                    string SSEND_AMP, 
                    string SSEND_PRV, 
                    string SSEND_ZIP, 
                    string SINS_NAME, 
                    string SINS_BUILD, 
                    string SINS_ADDR, 
                    string SINS_MOO, 
                    string SINS_SOI, 
                    string SINS_ROAD, 
                    string SINS_DIST, 
                    string SINS_AMP, 
                    string SINS_PRV, 
                    string SINS_ZIP) {
            this.TOKEN_ID = TOKEN_ID;
            this.SPHONE_NETW = SPHONE_NETW;
            this.SREF_NO1 = SREF_NO1;
            this.SRECV_DATE = SRECV_DATE;
            this.SRECV_AMT = SRECV_AMT;
            this.SSEND_NAME = SSEND_NAME;
            this.SSEND_ADDR = SSEND_ADDR;
            this.SSEND_DIST = SSEND_DIST;
            this.SSEND_AMP = SSEND_AMP;
            this.SSEND_PRV = SSEND_PRV;
            this.SSEND_ZIP = SSEND_ZIP;
            this.SINS_NAME = SINS_NAME;
            this.SINS_BUILD = SINS_BUILD;
            this.SINS_ADDR = SINS_ADDR;
            this.SINS_MOO = SINS_MOO;
            this.SINS_SOI = SINS_SOI;
            this.SINS_ROAD = SINS_ROAD;
            this.SINS_DIST = SINS_DIST;
            this.SINS_AMP = SINS_AMP;
            this.SINS_PRV = SINS_PRV;
            this.SINS_ZIP = SINS_ZIP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class P_RECV_TAX_MBLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="P_RECV_TAX_MBLResponse", Namespace="http://119.46.91.238/", Order=0)]
        public PWCF.Webservice_IDLT.P_RECV_TAX_MBLResponseBody Body;
        
        public P_RECV_TAX_MBLResponse() {
        }
        
        public P_RECV_TAX_MBLResponse(PWCF.Webservice_IDLT.P_RECV_TAX_MBLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://119.46.91.238/")]
    public partial class P_RECV_TAX_MBLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PWCF.Webservice_IDLT.DLT P_RECV_TAX_MBLResult;
        
        public P_RECV_TAX_MBLResponseBody() {
        }
        
        public P_RECV_TAX_MBLResponseBody(PWCF.Webservice_IDLT.DLT P_RECV_TAX_MBLResult) {
            this.P_RECV_TAX_MBLResult = P_RECV_TAX_MBLResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : PWCF.Webservice_IDLT.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<PWCF.Webservice_IDLT.ServiceSoap>, PWCF.Webservice_IDLT.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PWCF.Webservice_IDLT.LoginResponse PWCF.Webservice_IDLT.ServiceSoap.Login(PWCF.Webservice_IDLT.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string Username, string Password) {
            PWCF.Webservice_IDLT.LoginRequest inValue = new PWCF.Webservice_IDLT.LoginRequest();
            inValue.Body = new PWCF.Webservice_IDLT.LoginRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            PWCF.Webservice_IDLT.LoginResponse retVal = ((PWCF.Webservice_IDLT.ServiceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PWCF.Webservice_IDLT.P_CAL_TAX_MBLResponse PWCF.Webservice_IDLT.ServiceSoap.P_CAL_TAX_MBL(PWCF.Webservice_IDLT.P_CAL_TAX_MBLRequest request) {
            return base.Channel.P_CAL_TAX_MBL(request);
        }
        
        public PWCF.Webservice_IDLT.DLT P_CAL_TAX_MBL(
                    string TOKEN_ID, 
                    string SOFF_NAME, 
                    string SBR_NAME, 
                    string STYPE_NAME, 
                    string SPLATE1, 
                    string SPLATE2, 
                    string SID_NO, 
                    string SNAME, 
                    string STEL_NO, 
                    string SPOLICY_FLAG, 
                    string SPOLICY_NO, 
                    string SPOLICY_END, 
                    string SADV_FLAG, 
                    string SPHONE_NETW, 
                    string SIDTAX_NETW, 
                    string SOPR_PAY) {
            PWCF.Webservice_IDLT.P_CAL_TAX_MBLRequest inValue = new PWCF.Webservice_IDLT.P_CAL_TAX_MBLRequest();
            inValue.Body = new PWCF.Webservice_IDLT.P_CAL_TAX_MBLRequestBody();
            inValue.Body.TOKEN_ID = TOKEN_ID;
            inValue.Body.SOFF_NAME = SOFF_NAME;
            inValue.Body.SBR_NAME = SBR_NAME;
            inValue.Body.STYPE_NAME = STYPE_NAME;
            inValue.Body.SPLATE1 = SPLATE1;
            inValue.Body.SPLATE2 = SPLATE2;
            inValue.Body.SID_NO = SID_NO;
            inValue.Body.SNAME = SNAME;
            inValue.Body.STEL_NO = STEL_NO;
            inValue.Body.SPOLICY_FLAG = SPOLICY_FLAG;
            inValue.Body.SPOLICY_NO = SPOLICY_NO;
            inValue.Body.SPOLICY_END = SPOLICY_END;
            inValue.Body.SADV_FLAG = SADV_FLAG;
            inValue.Body.SPHONE_NETW = SPHONE_NETW;
            inValue.Body.SIDTAX_NETW = SIDTAX_NETW;
            inValue.Body.SOPR_PAY = SOPR_PAY;
            PWCF.Webservice_IDLT.P_CAL_TAX_MBLResponse retVal = ((PWCF.Webservice_IDLT.ServiceSoap)(this)).P_CAL_TAX_MBL(inValue);
            return retVal.Body.P_CAL_TAX_MBLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PWCF.Webservice_IDLT.P_RECV_TAX_MBLResponse PWCF.Webservice_IDLT.ServiceSoap.P_RECV_TAX_MBL(PWCF.Webservice_IDLT.P_RECV_TAX_MBLRequest request) {
            return base.Channel.P_RECV_TAX_MBL(request);
        }
        
        public PWCF.Webservice_IDLT.DLT P_RECV_TAX_MBL(
                    string TOKEN_ID, 
                    string SPHONE_NETW, 
                    string SREF_NO1, 
                    string SRECV_DATE, 
                    string SRECV_AMT, 
                    string SSEND_NAME, 
                    string SSEND_ADDR, 
                    string SSEND_DIST, 
                    string SSEND_AMP, 
                    string SSEND_PRV, 
                    string SSEND_ZIP, 
                    string SINS_NAME, 
                    string SINS_BUILD, 
                    string SINS_ADDR, 
                    string SINS_MOO, 
                    string SINS_SOI, 
                    string SINS_ROAD, 
                    string SINS_DIST, 
                    string SINS_AMP, 
                    string SINS_PRV, 
                    string SINS_ZIP) {
            PWCF.Webservice_IDLT.P_RECV_TAX_MBLRequest inValue = new PWCF.Webservice_IDLT.P_RECV_TAX_MBLRequest();
            inValue.Body = new PWCF.Webservice_IDLT.P_RECV_TAX_MBLRequestBody();
            inValue.Body.TOKEN_ID = TOKEN_ID;
            inValue.Body.SPHONE_NETW = SPHONE_NETW;
            inValue.Body.SREF_NO1 = SREF_NO1;
            inValue.Body.SRECV_DATE = SRECV_DATE;
            inValue.Body.SRECV_AMT = SRECV_AMT;
            inValue.Body.SSEND_NAME = SSEND_NAME;
            inValue.Body.SSEND_ADDR = SSEND_ADDR;
            inValue.Body.SSEND_DIST = SSEND_DIST;
            inValue.Body.SSEND_AMP = SSEND_AMP;
            inValue.Body.SSEND_PRV = SSEND_PRV;
            inValue.Body.SSEND_ZIP = SSEND_ZIP;
            inValue.Body.SINS_NAME = SINS_NAME;
            inValue.Body.SINS_BUILD = SINS_BUILD;
            inValue.Body.SINS_ADDR = SINS_ADDR;
            inValue.Body.SINS_MOO = SINS_MOO;
            inValue.Body.SINS_SOI = SINS_SOI;
            inValue.Body.SINS_ROAD = SINS_ROAD;
            inValue.Body.SINS_DIST = SINS_DIST;
            inValue.Body.SINS_AMP = SINS_AMP;
            inValue.Body.SINS_PRV = SINS_PRV;
            inValue.Body.SINS_ZIP = SINS_ZIP;
            PWCF.Webservice_IDLT.P_RECV_TAX_MBLResponse retVal = ((PWCF.Webservice_IDLT.ServiceSoap)(this)).P_RECV_TAX_MBL(inValue);
            return retVal.Body.P_RECV_TAX_MBLResult;
        }
    }
}
